no_body_crop: false

optim_flame:
  steps: 1001
  share_id: true
  # Loss weights for FLAME optimization
  lambda_lmk_2d: 1.0
  lambda_lmk_203: 1.0
  lambda_shape_reg: 0.01
  lambda_exp_reg: 0.01
  lambda_pose_reg: 1.0
  lambda_motion_reg: 10.0

  # mini batch for video
  mini_batch_size: 1024
  share_pose: false

optim_ehm:
  steps: 1001
  share_id: true

  # mini batch for video
  mini_batch_size: 1024
  share_pose: false

  # optim
  optim_camera: true

  # Loss weights for EHM/SMPL-X optimization
  lambda_3d_head: 5.0
  lambda_3d_hand_l: 0.25
  lambda_3d_hand_r: 0.25
  lambda_3d_z: 2.5
  lambda_2d_kpt: 0.2

  lambda_prior: 10.0
  lambda_smplx_shape_reg: 0.1
  lambda_mano_shape_reg: 0.1
  lambda_scale_reg: 100.0
  lambda_joint_offset_reg: 10000.0

  # regularize change from init pose
  lambda_smplx_pose: 0.1

  # invisible lower-body regularization
  lambda_smplx_pose_reg_base: 100.0
  lambda_smplx_leg_pose: 400.0
  lambda_smplx_freezed_pose: 400.0

  # hand
  lambda_smplx_hand_pose_reg: 0.1

  # temporal motion
  lambda_mtn_body_pose: 200.0
  lambda_mtn_rot6d: 100.0
  lambda_mtn_trans: 100.0
  lambda_mtn_trans_z: 100.0
  lambda_mtn_vertices: 1.0
