# no body crop for scan, use full image w/ gt camera
no_body_crop: true

optim_flame:
  steps: 1001
  share_id: true
  # Loss weights for FLAME optimization
  lambda_lmk_2d: 1.0
  lambda_lmk_203: 1.0
  lambda_shape_reg: 0.01
  lambda_exp_reg: 0.01
  lambda_pose_reg: 1.0

  # no motion for scan
  lambda_motion_reg: 0.0

  # no mini batch for scan
  mini_batch_size: -1
  # share pose for scan from multi-view
  share_pose: true

optim_ehm:
  steps: 1001
  share_id: true

  # no mini batch for scan
  mini_batch_size: -1
  # share pose for scan from multi-view
  share_pose: true

  # optim
  optim_camera: false

  # Loss weights for EHM/SMPL-X optimization
  lambda_3d_head: 5.0
  lambda_3d_hand_l: 0.25
  lambda_3d_hand_r: 0.25
  lambda_3d_z: 2.5
  lambda_2d_kpt: 0.2

  lambda_prior: 1.0
  lambda_smplx_shape_reg: 0.1
  lambda_mano_shape_reg: 0.1
  lambda_scale_reg: 100.0
  lambda_joint_offset_reg: 10000.0

  # regularize change from init pose
  lambda_smplx_pose: 10.0

  # invisible lower-body regularization
  lambda_smplx_pose_reg_base: 1.0
  lambda_smplx_leg_pose: 1.0
  lambda_smplx_freezed_pose: 1.0

  # hand
  lambda_smplx_hand_pose_reg: 0.1

  # no temporal motion for scan
  lambda_mtn_body_pose: 0.0
  lambda_mtn_rot6d: 0.0
  lambda_mtn_trans: 0.0
  lambda_mtn_trans_z: 0.0
  lambda_mtn_vertices: 0.0
