# no body crop for scan, use full image w/ gt camera
no_body_crop: true
# reset to use base track results
reset_to_base_track: true

optim_flame:
  steps: 101
  share_id: true

  # mini batch for video
  mini_batch_size: 1024
  share_pose: false

  # Loss weights for FLAME optimization
  lambda_lmk_2d: 1.0
  lambda_lmk_203: 1.0
  lambda_shape_reg: 0.01
  lambda_exp_reg: 0.01
  lambda_pose_reg: 1.0

  # motion reg for video
  lambda_motion_reg: 0.01

optim_ehm:
  steps: 501  # 1001
  share_id: true

  # mini batch for video
  mini_batch_size: 1024
  share_pose: false

  # optim
  optim_camera: true

  # Loss weights for EHM/SMPL-X optimization
  lambda_3d_head: 10.0
  lambda_3d_hand_l: 10.0
  lambda_3d_hand_r: 10.0
  lambda_3d_z: 0.1
  lambda_2d_kpt: 10.0
  lambda_2d_knee_feet: 100.0  # 10.0x of lambda_2d_kpt

  lambda_prior: 1.0
  lambda_smplx_shape_reg: 0.1
  lambda_mano_shape_reg: 0.1
  lambda_scale_reg: 100.0
  lambda_joint_offset_reg: 1.0

  # regularize change from init pose
  lambda_smplx_pose: 10.0
  lambda_smplx_init: 10.0  # Weight for regularizing invalid hands/face towards init pose

  # invisible lower-body regularization
  lambda_smplx_pose_reg_base: 1.0
  lambda_smplx_leg_pose: 1.0
  lambda_smplx_freezed_pose: 1.0

  # hand
  lambda_smplx_hand_pose_reg: 0.1

  # temporal motion
  lambda_mtn_body_pose: 100.0
  lambda_mtn_rot6d: 100.0
  lambda_mtn_trans: 100.0
  lambda_mtn_trans_z: 100.0
  lambda_mtn_vertices: 10.0

